#!/bin/sh
# List running instances in each node
#
# not up-to-date
#
echo blenders em n0:
ssh n0 ps -aux | grep $USER | grep blender | grep -v grep | grep -v ssh
echo blenders em n1:
ssh n1 ps -aux | grep $USER | grep blender | grep -v grep | grep -v ssh
echo blenders em n10:
ssh n10 ps -aux | grep $USER | grep blender | grep -v grep | grep -v ssh
echo blenders em n11:
ssh n11 ps -aux | grep $USER | grep blender | grep -v grep | grep -v ssh
