#!/bin/sh
### General Options ###
#PBS -N Blender-Client-N0
#PBS -V
#PBS -r n
### Resource Handling ###
#PBS -l nodes=1:ppn=1:blender0
#PBS -q batch
#PBS -l walltime=23:00:00
### Output Stream Options ### 

### Bash script ###
echo ""
echo Blender-Cliente em `hostname`
echo ""

myblender="blender -b -noaudio"
$myblender bloco.blend -o /home/cirochang/block_ -F AVIJPEG -x 1 -P Client.py

exit 0

