#!/bin/sh
### General Options ###
#PBS -N Blender-Master-N0-1
#PBS -V
#PBS -r n
### Resource Handling ###
#PBS -l nodes=1:ppn=1:blender0
#PBS -q batch
#PBS -l walltime=23:00:00
### Output Stream Options ### 

### Bash script ###
echo ""
echo Blender-Mestre 1 em `hostname`
echo ""

chmod 0700 Master.py Slave.py Client.py bloco.blend
touch Master.py Slave.py Client.py bloco.blend
myblender="blender -b -noaudio"
$myblender -P Master.py

exit 0
